name: 'terraform-Azure'

on:
  push:
    branches:
      - main
  workflow_dispatch: #this attribute will enable the manual run to the pipeline
# Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
permissions:
      id-token: write
      contents: read

defaults:
  run:
    shell: bash
jobs:
  terraform_plan:
    name: 'terraform test'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

       # Log into Azure with OIDC integration
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
        
 
    - name: terraform init
      run: terraform init
 
    - name: terraform Plan
      run: terraform plan 
      
